version: 2.1

executors:
  aws-executor:
    docker:
      - image: amazon/aws-cli:2.12.0  # AWS CLI Docker image for executing CloudFormation commands

jobs:
  # Job to deploy the CloudFormation stack
  deploy:
    executor: aws-executor
    steps:
      # Checkout the code from the repository
      - checkout

      # Validate the CloudFormation template to ensure it's correct
      - run:
          name: Validate CloudFormation Template
          command: |
            aws cloudformation validate-template \
              --template-body file://s3-buckets-template.yml

      # Deploy the CloudFormation stack to create the S3 buckets
      - run:
          name: Deploy CloudFormation Template
          command: |
            aws cloudformation deploy \
              --template-file s3-buckets-template.yml \
              --stack-name s3-buckets-stack \
              --capabilities CAPABILITY_NAMED_IAM

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy  # Execute the deploy job in the workflow
